sudo: required
services:
  - docker
  
before_install:
  - docker build -t fanlima/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fanlima/react-test npm test

after_sucess:
  - docker build -t fanlima/multi-client ./client
  - docker build -t fanlima/multi-nginx ./nginx
  - docker build -t fanlima/multi-server ./server
  - docker build -t fanlima/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fanlima/multi-client
  - docker push fanlima/multi-nginx
  - docker push fanlima/multi-server
  - docker push fanlima/multi-worker

  
